[package]
name = "dezoomify-rs"
version = "2.2.0"
authors = ["lovasoa"]
edition = "2018"
license-file = "LICENSE"
description = "Allows downloading zoomable images. Supports several different formats such as zoomify, iiif, and deep zoom images."
documentation = "https://docs.rs/dezoomify-rs"
repository = "https://github.com/lovasoa/dezoomify-rs"
readme = "README.md"
keywords = ["image", "download"]

[dependencies]
image = "0.23"
png = "0.16"
reqwest = { version = "0.10", features = ["gzip"] }
tokio = { version = "0.2", features = ["rt-threaded", "rt-core", "macros", "rt-util", "time", "fs", "sync"] }
futures = "0.3"
custom_error = "1.7"
structopt = "0.3"
evalexpr = "5.0"
regex = "1"
lazy_static = "1.3"
itertools = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde-xml-rs = "0.4"
serde_json = "1.0"
serde_urlencoded = "0.6"
block-modes = "0.4"
aes = "0.4"
hmac = "0.7"
sha-1 = "0.8"
base64 = "0.12"
indicatif = "0.14"
sanitize-filename-reader-friendly = "0.9"
colour = "0.5"
human-panic = "1"
log = "0.4"
env_logger = "0.7"
url = "2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "local_dezoomifying"
harness = false