on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            binary_path: target/release/dezoomify-rs.exe
          - os: macos-latest
            binary_path: target/release/dezoomify-rs
          - os: ubuntu-latest
            binary_path: target/release/dezoomify-rs
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable, override: true}
      - name: build
        uses: actions-rs/cargo@v1
        with: { command: build, args: --release }
      - uses: actions/upload-artifact@v1
        with:
          name: dezoomify-rs ${{ matrix.os }}
          path: ${{ matrix.binary_path }}
  create_release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: get commit message
        run: echo ::set-env name=commitmsg::$(git tag --format='%(subject)' -l | tail -n 1)
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{Â env.commitmsg }}
          draft: false
          prerelease: false

      - uses: actions/download-artifact@v1
        with: { name: dezoomify-rs windows-latest, path: . }
      - name: Upload Windows binary
        uses: lovasoa/upload-release-asset@851d9cc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dezoomify-rs.exe
          asset_name: dezoomify-rs.exe
          asset_label: Dezoomify-rs for Windows
          asset_content_type: application/vnd.microsoft.portable-executable

      - uses: actions/download-artifact@v1
        with: { name: dezoomify-rs macos-latest, path: . }
      - name: Upload MacOs binary
        uses: lovasoa/upload-release-asset@851d9cc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dezoomify-rs
          asset_name: dezoomify-rs
          asset_label: Dezoomify-rs for MacOS
          asset_content_type: application/octet-stream

      - uses: actions/download-artifact@v1
        with: { name: dezoomify-rs ubuntu-latest, path: . }
      - name: Upload Linux binary
        uses: lovasoa/upload-release-asset@851d9cc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dezoomify-rs
          asset_name: dezoomify-rs-linux
          asset_label: Dezoomify-rs for Linux
          asset_content_type: application/octet-stream
